### ISSUE TITLE
Any way we could exclude the mute button?

### ISSUE THREAD

**Issue by anghelos** [Egor3f/streamkeys-quantum#3]
Hi there,

Love the extension, but I disabled it because it wouldn't allow me to globally mute my laptop any longer, which is important in most of my work settings.

(the new temporary disabling option is good, but I really would prefer completely excluding the mute button. I believe having it mute a single audio source is less useful in most cases).

Thanks for the great work!

**Comment by Egor3f** [comment]
Hi @anghelos , I agree with you that it's much more useful to mute the whole computer than specific source. Please, test this version https://github.com/Egor3f/streamkeys-quantum/releases/download/1.7.6.2/StreamKeys_Firefox_Quantum_nomute.exe

**Comment by Egor3f** [comment]
When I have enough time I will add key configuration dialog to extension, like in original StreamKeys for Chrome

**Comment by anghelos** [comment]
Thanks! This works great.

**Comment by Egor3f** [comment]
Mute button is now configurable as long as all the others
https://github.com/Egor3f/streamkeys-quantum/releases/tag/1.1.180
