### ISSUE TITLE
Pause does not work globally

### ISSUE THREAD

**Issue by ZOrangeBandit** [Egor3f/streamkeys-quantum#4]
As the title says, the pause key does not work when the window is not selected, and will only pause what is playing for about half a second. This error occurs in YouTube, and I have not tried it on any other sites.

**Comment by aglogger** [comment]
For me play/pause is not working aswell (Even when i have for example a YouTube tab focused). Skipping to next track is working just fine.

**Comment by Egor3f** [comment]
Please, try to check any other music site except Youtube, and let me know, if the issue remains

**Comment by JosiahBradley** [comment]
Just tested in FireFox 73.0.1 with add-on version 1.1.180 . Pause/play works as expected in YouTube. Running Windows 10 18363.657 v1909

Edit: I was actually testing on YouTube Music. Confirmed it works on native YouTube as well.
