### ISSUE TITLE
Temporarily disable streamkeyhelper with shortcut keys

### ISSUE THREAD

**Issue by aglogger** [Egor3f/streamkeys-quantum#5]
Is there a possiblity for disabling the streamkeyhelper.exe temporarily by using a shortcut key instead of clicking the icon in the tray.

**Comment by Egor3f** [comment]
Hey @aglogger !
It's possible in new version: https://github.com/Egor3f/streamkeys-quantum/releases/tag/1.1.180
Buy you should configure it manually using Au3 syntax (it's easy and there is a help link at the options page)
