### ISSUE TITLE
Add support for Bluetooth devices

### ISSUE THREAD

**Issue by Sv443** [Egor3f/streamkeys-quantum#7]
I've started using this App/Extension to be able to control YouTube through my Bluetooth speaker but it currently doesn't seem to work.  
Is there any way you could add support for capturing Bluetooth media controls?

**Comment by anghelos** [comment]
Funnily enough, it works from my bluetooth speaker, but not my bluetooth keyboard. I'm thinking maybe there are multiple keycodes for the media keys?

**Comment by Sv443** [comment]
Apparently there are a ton of different so called "Bluetooth profiles" for different devices and purposes: https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles  
Maybe only a small selection of them are working with Streamkeys.

**Comment by Egor3f** [comment]
> 
> 
> Funnily enough, it works from my bluetooth speaker, but not my bluetooth keyboard. I'm thinking maybe there are multiple keycodes for the media keys?

I'll add key remapping in the next version

**Comment by Sv443** [comment]
My Bluetooth speaker now works. I don't know why it didn't work before though.  
I don't know if I should close this issue due to the comment above so just close it if you want to.
