### ISSUE TITLE
Not working with latest Firefox Developer Edition.

### ISSUE THREAD

**Issue by ZeroCool940711** [Egor3f/streamkeys-quantum#8]
As the title says Streamkeys Quantum is not working with the latest firefox developer edition version, I know its normal to have addons not working on the latest developer edition but would be nice if this extension could be fixed, I love this extension and can't really find anything else that works globally, I can not use the normal firefox stable release and would really appreciate if this could work on the development edition. So far what I see is that firefox is not launching the `streamkeyshelper.exe` when it launches as it was doing before, also I'm pretty sure before the extension was installed on firefox and now its not been installed, .Thanks in advance.

**Comment by Egor3f** [comment]
It's a change in Mozilla sideload policy, I'll think how I can bypass it.
It's strange decision: 
- mozilla does not allow to configure global hotkeys (unlike chrome does), so I have to use additinal exe file
- mozilla does not allow to ship additional exe files to store along with extension
- now mozilla does not allow to install extensions from local sources using sideload...

Of course there are still some ways to install unpublished extension, but they are much less convinient for the end-user
