### ISSUE TITLE
Issue reinstalling after deleting profile

### ISSUE THREAD

**Issue by Elsarild** [Egor3f/streamkeys-quantum#9]
I wanted to try this out before switching away from Brave, installed and it worked perfectly.

To prepare for the switch i deleted my firefox profile and set up everything how I wanted it, uninstalled Streamkeys Quantum, then installed it again, but now the extension dosen't show up in firefox at all.

I've tried uninstalling firefox, and streamkeys as well as creating new profiles but I can't make it work anymore.

**Comment by Egor3f** [comment]
Unfortunately, Mozilla has completely disabled extension sideloading.
Some information is mentioned in this issue: #8 
As a **temporary** solution you can install the extension using link: https://files.efprojects.com/mozilla-sideload/skq@efprojects.com.xpi
Firstly, install extension as usually, (by launching exe from releases page, if you haven't done it before)
Secondly, open Firefox and visit the link mentioned above
Then, agree with all prompts and enjoy music control! :)

When I have some spare time, I'll try to automate this process using InnoSetup
